### ISSUE TITLE
Disqus integration broken if pelican site is served over https

### ISSUE THREAD

**Issue by mekkagodzilla** [gfidente/pelican-svbhack#22]
Simple fix though. In the article template, remove http in line 34, letting the url start with //.
It will use the same protocol as the site.

**Comment by gfidente** [comment]
hi, thanks for reporting this

I get the change is minimal, but maybe you want to push the change yourself with a pull request?

**Comment by mekkagodzilla** [comment]
Hi there,
I've never done a pull request, I’m just a pleb user.
Looking over the doc about this, it seems quite a lot of work to get 4 characters deleted in a file.

Regards,
Phil

**Comment by gfidente** [comment]
hi Phil,

my point is that you get to have your name assigned on the bug and the commit message with the fix for it.

To me, it's not about how many lines or characters you have to change, it's more about finding and understanding the issue and know how to fix it.

**Comment by mekkagodzilla** [comment]
It was not that hard after all.
Thanks for the learning experience.

**Comment by gfidente** [comment]
Great, thanks for helping!
