### ISSUE TITLE
In Pelican >= 4.0 the format() command needs explicit keyword arguments

### ISSUE THREAD

**Issue by moorepants** [gfidente/pelican-svbhack#31]
For example, in `category.html`:
```
{% block head %}
{% if CATEGORY_FEED_ATOM %}
<link href="{{ FEED_DOMAIN }}/{{ CATEGORY_FEED_ATOM|format(category.slug) }}" type="application/atom+xml" rel="alternate" title="{{ SITENAME }} {{ category }} Category Atom" />
{% endif %}
{% if CATEGORY_FEED_RSS %}
<link href="{{ FEED_DOMAIN }}/{{ CATEGORY_FEED_RSS|format(category.slug) }}" type="application/rss+xml" rel="alternate" title="{{ SITENAME }} {{ category }} Category RSS" />
{% endif %}
{% endblock %}
```

`format(category.slug)` needs to be `format(slug=category.slug)`

**Comment by gfidente** [comment]
hi @moorepants thanks for pinging

I haven't tested the theme with pelican >= 4 yet, are you able to help with that and eventually provide a PR or prefer me to?

**Comment by moorepants** [comment]
I actually just switched themes so, I no longer have motivation to work on it. Sorry (thanks for the nice theme though).
