### ISSUE TITLE
best practice using {% block header %}{% endblock header %}

### ISSUE THREAD

**Issue by Carpintonto** [gfidente/pelican-svbhack#38]
Thanks for the great template.  

I am brand new to Pelican and not sure how it picks up custom template modifications using additional files.  I moved the row of links to the ending_message div and entered a string literal in its place [shown here](https://moonchat.space/enter-chatting.html).

I tried adding header.html to the template directory
`{% extends "base.html" %}
{% block header %}<h1>something to bark at</h1>}{% endblock header%}`

I think I need to tell Pelican to recognize the new file?

**Comment by Carpintonto** [comment]
I love it when [the lights come on](https://moonchat.space/category/misc.html).  I see how that block is used, and I don't want to break it!  Thank you!

**Comment by gfidente** [comment]
I might have missed this or misunderstood the intent, feel free to comment further or reopen if you see a specific issue

**Comment by Carpintonto** [comment]
At first I didn't see how your theme populates block header. Then I learned.

Great theme, and an excellent example for a beginner - thank you!
